add_newline = false

[username]
style_user="white bold"
format="$user($style)"
show_always=true

[hostname]
ssh_only=false
format="@$hostname:"
disabled=false

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"
